### ISSUE TITLE
[BUG] size has no effect when creating a terminal and recording?

### ISSUE THREAD

**Issue by pawamoy** [bczsalba/pytermgui#68]
**Describe the bug**
See #67 (same code):

```python
from io import StringIO
import pytermgui as ptg

code = """
while True:
    if condition:
        print("Hello")
    else:
        print("Goodbye")

    input()
"""

with ptg.Terminal(stream=StringIO(), size=(20, 20)).record() as recorder:
    recorder.write(ptg.tim.parse(ptg.highlight_python(code)))
    print(recorder.export_svg(inline_styles=True))
```

I can't seem to get the desired size for the generated SVG. It seems it uses my actual terminal size (vertical screen) rather than what I'm providing using the `size` parameter (zoomed out to see the full size):

![pytermgui2](https://user-images.githubusercontent.com/3999221/170481804-ab9fc6ae-1d13-49ee-93df-9166773e6c09.png)

**Expected behavior**
Respect the `size` value of the terminal when exporting a record to SVG.

**System information**

```
PyTermGUI version 6.2.1

System details:
    Python version: 3.8.13
    $TERM:          xterm-256color
    $COLORTERM:     truecolor
    Color support:  ColorSystem.TRUE
    OS Platform:    Linux-5.17.9-arch1-1-x86_64-with-glibc2.35
```

**Comment by bczsalba** [comment]
There is a bit of weirdness with how `Terminal`s are handled in the library, and it will be focused on in the new documentations. Basically, there exists a global terminal that basically everything uses to write/read information to, and it can be set using the `ptg.set_global_terminal` function.

This shouldn't affect your use case, but it seems it does, since changing it to this:

```python3
terminal = ptg.Terminal(stream=StringIO(), size=(20, 20))
ptg.set_global_terminal(terminal)

with terminal.record() as recorder:
    recorder.write(ptg.tim.parse(ptg.highlight_python(code)))
    recorder.save_svg(inline_styles=True)
```

Seems to work perfectly well. Will look into it further, but using it this way should help for now.
