### ISSUE TITLE
[BUG]sequences error

### ISSUE THREAD

**Issue by RshaCuDeVidro** [bczsalba/pytermgui#99]
←[1m←[36mPy←[90mTe←[37mrm←[37mGU←[37mI←[39m←[0m←[0m version ←[37m7.2.0←[0m

←[37m←[1mSystem details:←[0m
←[37m    Python version: ←[39m←[37m3.10.6←[0m
←[37m    $TERM:          ←[39m←[37mNone←[0m
←[37m    $COLORTERM:     ←[39m←[37mNone←[0m
←[37m    Color support:  ←[39m←[37mColorSystem.STANDARD←[0m
←[37m    OS Platform:    ←[39m←[37mWindows-10-10.0.19044-SP0←[0m

**Comment by bczsalba** [comment]
This is an issue on Windows' side, but should be relatively easy to fix. [Here](https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling) is a forum post about it, but since I don't have a Windows machine that exhibits this problem I can't trial it. If you figure out how to fix it, please let me know!
